//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreekFire.NHibernateConsole.GreekFireServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GreekFireServices.ExpenseFacade")]
    public interface ExpenseFacade {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExpenseFacade/GetExpenses", ReplyAction="http://tempuri.org/ExpenseFacade/GetExpensesResponse")]
        GreekFire.Domain.ExpenseDto[] GetExpenses();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ExpenseFacadeChannel : GreekFire.NHibernateConsole.GreekFireServices.ExpenseFacade, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ExpenseFacadeClient : System.ServiceModel.ClientBase<GreekFire.NHibernateConsole.GreekFireServices.ExpenseFacade>, GreekFire.NHibernateConsole.GreekFireServices.ExpenseFacade {
        
        public ExpenseFacadeClient() {
        }
        
        public ExpenseFacadeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpenseFacadeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpenseFacadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpenseFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GreekFire.Domain.ExpenseDto[] GetExpenses() {
            return base.Channel.GetExpenses();
        }
    }
}
