//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GreekFireExpenseDBModel", "FK_ExpenseLineItems_Expense_GreekFireExpense_Expenses", "Expenses", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GreekFireExpense.Data.EntityFramework.Expenses), "ExpenseLineItems", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GreekFireExpense.Data.EntityFramework.ExpenseLineItems))]

// Original file name:
// Generation date: 2/20/2009 12:14:43 AM
namespace GreekFireExpense.Data.EntityFramework
{
    
    /// <summary>
    /// There are no comments for GreekFireExpenseDBEntities in the schema.
    /// </summary>
    public partial class GreekFireExpenseDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new GreekFireExpenseDBEntities object using the connection string found in the 'GreekFireExpenseDBEntities' section of the application configuration file.
        /// </summary>
        public GreekFireExpenseDBEntities() : 
                base("name=GreekFireExpenseDBEntities", "GreekFireExpenseDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GreekFireExpenseDBEntities object.
        /// </summary>
        public GreekFireExpenseDBEntities(string connectionString) : 
                base(connectionString, "GreekFireExpenseDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GreekFireExpenseDBEntities object.
        /// </summary>
        public GreekFireExpenseDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "GreekFireExpenseDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ExpenseLineItems in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ExpenseLineItems> ExpenseLineItems
        {
            get
            {
                if ((this._ExpenseLineItems == null))
                {
                    this._ExpenseLineItems = base.CreateQuery<ExpenseLineItems>("[ExpenseLineItems]");
                }
                return this._ExpenseLineItems;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ExpenseLineItems> _ExpenseLineItems;
        /// <summary>
        /// There are no comments for Expenses in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Expenses> Expenses
        {
            get
            {
                if ((this._Expenses == null))
                {
                    this._Expenses = base.CreateQuery<Expenses>("[Expenses]");
                }
                return this._Expenses;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Expenses> _Expenses;
        /// <summary>
        /// There are no comments for ExpenseLineItems in the schema.
        /// </summary>
        public void AddToExpenseLineItems(ExpenseLineItems expenseLineItems)
        {
            base.AddObject("ExpenseLineItems", expenseLineItems);
        }
        /// <summary>
        /// There are no comments for Expenses in the schema.
        /// </summary>
        public void AddToExpenses(Expenses expenses)
        {
            base.AddObject("Expenses", expenses);
        }
    }
    /// <summary>
    /// There are no comments for GreekFireExpenseDBModel.ExpenseLineItems in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GreekFireExpenseDBModel", Name="ExpenseLineItems")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ExpenseLineItems : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ExpenseLineItems object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="amount">Initial value of Amount.</param>
        /// <param name="description">Initial value of Description.</param>
        public static ExpenseLineItems CreateExpenseLineItems(long id, decimal amount, string description)
        {
            ExpenseLineItems expenseLineItems = new ExpenseLineItems();
            expenseLineItems.Id = id;
            expenseLineItems.Amount = amount;
            expenseLineItems.Description = description;
            return expenseLineItems;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Amount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnAmountChanging(value);
                this.ReportPropertyChanging("Amount");
                this._Amount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Amount");
                this.OnAmountChanged();
            }
        }
        private decimal _Amount;
        partial void OnAmountChanging(decimal value);
        partial void OnAmountChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Expenses in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GreekFireExpenseDBModel", "FK_ExpenseLineItems_Expense_GreekFireExpense_Expenses", "Expenses")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Expenses Expenses
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Expenses>("GreekFireExpenseDBModel.FK_ExpenseLineItems_Expense_GreekFireExpense_Expenses", "Expenses").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Expenses>("GreekFireExpenseDBModel.FK_ExpenseLineItems_Expense_GreekFireExpense_Expenses", "Expenses").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Expenses in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Expenses> ExpensesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Expenses>("GreekFireExpenseDBModel.FK_ExpenseLineItems_Expense_GreekFireExpense_Expenses", "Expenses");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Expenses>("GreekFireExpenseDBModel.FK_ExpenseLineItems_Expense_GreekFireExpense_Expenses", "Expenses", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GreekFireExpenseDBModel.Expenses in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GreekFireExpenseDBModel", Name="Expenses")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Expenses : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Expenses object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="title">Initial value of Title.</param>
        public static Expenses CreateExpenses(long id, string description, string title)
        {
            Expenses expenses = new Expenses();
            expenses.Id = id;
            expenses.Description = description;
            expenses.Title = title;
            return expenses;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for ExpenseLineItems in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GreekFireExpenseDBModel", "FK_ExpenseLineItems_Expense_GreekFireExpense_Expenses", "ExpenseLineItems")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ExpenseLineItems> ExpenseLineItems
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ExpenseLineItems>("GreekFireExpenseDBModel.FK_ExpenseLineItems_Expense_GreekFireExpense_Expenses", "ExpenseLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ExpenseLineItems>("GreekFireExpenseDBModel.FK_ExpenseLineItems_Expense_GreekFireExpense_Expenses", "ExpenseLineItems", value);
                }
            }
        }
    }
}
